#!/bin/bash

DEFAULT_COMMIT_MESSAGE="Aggiunto"

# build the client
cd client
npm run build 
cd ..

# build server API
cd server
npm run build
cd ..

if [ $# -eq 0 ]; then
    COMMIT_MESSAGE="$DEFAULT_COMMIT_MESSAGE"
else
    COMMIT_MESSAGE="$1"
fi

git pull
git add *
git commit -m "$COMMIT_MESSAGE"
git push
